# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(default=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('target_url', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='not sent', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Group')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Client')),
            ],
        ),
        migrations.AddField(
            model_name='permissionresponse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notification.User'),
        ),
        migrations.AddField(
            model_name='notificationresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.User'),
        ),
        migrations.AddField(
            model_name='notification_queue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.User'),
        ),
        migrations.AddField(
            model_name='ask_permission',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.Permission'),
        ),
        migrations.AddField(
            model_name='ask_permission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notification.User'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('name', 'client')]),
        ),
    ]
